### ISSUE TITLE
Не открываются сериалы

### ISSUE THREAD

**Issue by m190** [vlmaksime/plugin.video.filmix#1]
Добрый день,

спасибо за классный плагин! Единственный недостаток - не работают сериалы. Например Доктор плюшева: https://filmix.co/music/87760-doktor-plyusheva-doc-mcstuffins-multserial-2012-.html

**Comment by vlmaksime** [comment]
Добрый день.
Проверьте версию дополнения. На версии 1.2.5 у отображаются сезоны и запускаются серии.

**Comment by m190** [comment]
Спасибо за быстрый ответ. Вечером проверю. Вчера отображалось 1.2.4 и почему-то не хотело обновляться.

**Comment by m190** [comment]
В версии 1.2.5 тоже не работает. После выборов сериала отображается пустой экран с одной строчкой: три точки.

**Comment by vlmaksime** [comment]
По возможности, проверьте доступность сериала с помощью мобильного приложения. Возможно у Вас материал не доступен из-за правообладателя.
Для анализа проблемы мне нужны Ваши логи.
Необходимые шаги:
1. Из официального репозитория установить дополнение [Kodi Logfile Uploader](https://kodi.tv/addon/program-add-ons-scripts/kodi-logfile-uploader)
2. В настройках зайти в раздел "Система"-"Логирование" и включить пункт "Включить журнал отладки"
3. Воспроизвести проблему
4. После этого зайти в программные дополнения, выбрать "Kodi Logfile Uploader" и загрузить файл. Дополнение выдаст ссылку на загруженный файл. Мне нужна эта ссылка.

**Comment by m190** [comment]
На мобильном приложении все работает. В плагине проблема только с сериалами. Логи можете найти тут: https://paste.kodi.tv/jolofihaxo

**Comment by vlmaksime** [comment]
С логами все в порядке. Есть у меня еще одно предположение, надеюсь верное.
Зайдите в сериал, вызовите боковое меню. В скине Estuary (остальных наверно так же) в предпоследнем пункте есть переключатель. Он переключает между режимами "Все видео", "Просмотрено", "Не просмотрено". Предполагаю, что у Вас сейчас переключатель находится в состоянии "Просмотрено"

**Comment by m190** [comment]
Точно, спасибо большое! Видимо ребенок что-то понажимал :) Спасибо за полезный плагин!
