### ISSUE TITLE
Проблемы с поиском

### ISSUE THREAD

**Issue by Durlyn** [vlmaksime/plugin.video.filmix#11]
Привет!
появилась странная проблема. поиск иногда работает, иногда пустой список выдает. вроде уже как-то чинили эту проблему. в логах ничего не пишет по ошибкам.

**Comment by AKotov-dev** [comment]
@Durlyn 

`Kodi-v21.0a2-Omega`
Привет. Было такое. Почистил у себя кеш и перегрузился, вроде ушла эта бяка. Использовал [ROCK CLEANER CLASSIC](https://iwf1.com/kodi/program.RockCleaner-Classic). Может быть опять вылезет, не знаю, но пока работает.

**Comment by Durlyn** [comment]
да. спасибо. вроде заработало.
