### ISSUE TITLE
SSL certificate error

### ISSUE THREAD

**Issue by m190** [vlmaksime/plugin.video.filmix#2]
Все реквесты на сервер закончатся неуспешно с ошибкой 400 The SSL certificate error.

**Comment by vlmaksime** [comment]
Уже исправлено [обновлением сертификата](https://github.com/vlmaksime/plugin.video.filmix/commit/48df1dcf3db205f8c9de075f15dacf076bceb27c). Попробуйте обновиться из репозитория.

**Comment by m190** [comment]
Пишет, что последняя версия 1.2.8. Будете релисовать новую с исправлением?

**Comment by vlmaksime** [comment]
Обновилось дополнение "Filmix certificates" (script.module.filmix.cert) до версии 0.9.4. Версия дополнения Filmix осталась без изменения.
По идее дополнение должно обновиться сразу после принудительного запуска обновления репозитория. Или можете скачать нужную версию по ссылке [script.module.filmix.cert-0.9.4.zip](https://vlmaksime.github.io/repository.vlmaksime/releases/script.module.filmix.cert/script.module.filmix.cert-0.9.4.zip)
