### ISSUE TITLE
Больше не показывает обложки.

### ISSUE THREAD

**Issue by newdanceradio** [vlmaksime/plugin.video.filmix#3]
Перестали показываться обложки.

**Comment by vlmaksime** [comment]
Поправил в релизе v1.2.12

**Comment by newdanceradio** [comment]
Спасибо, обложки появились, 
![20210419_185205](https://user-images.githubusercontent.com/17381301/115266693-17d95f80-a141-11eb-806c-ef2ca4af01ff.jpg)

но не везде.

![20210419_185216](https://user-images.githubusercontent.com/17381301/115266422-dd6fc280-a140-11eb-817e-d7d74fd5f209.jpg)
![20210419_185232](https://user-images.githubusercontent.com/17381301/115266432-df398600-a140-11eb-8359-cc89cf8d70e1.jpg)
