### ISSUE TITLE
ERROR: plugin.video.filmix [v.1.4.4~beta4]: 400 Client Error

### ISSUE THREAD

**Issue by linoobs** [vlmaksime/plugin.video.filmix#9]
Сегодня стало выпадать в ошибку, в логе ERROR: plugin.video.filmix [v.1.4.4~beta4]: 400 Client Error: Bad Request for url: http://filmixapp.cyou/api/v2/user_profile?user_dev_name=Kodi+18.4+%28e5ded%29&user_dev_os=Windows+10&user_dev_token=ad1a03a02b05367ec9df57

**Comment by vlmaksime** [comment]
Исправлено в версии [1.4.4](https://github.com/vlmaksime/plugin.video.filmix/releases/tag/v1.4.4)
Исправление уже загружено в репозиторий. Попробуйте обновиться из репозитория дополнений
